todoproject1/todoproject/todoapp/urls.py
from . import views
from django.urls import path

app_name= "todoapp"

urlpatterns = [

    path('',views.home,name='home'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('cbvhome/',views.Tasklistview.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/', views.Taskdetailview.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.Taskupdateview.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.Taskdeleteview.as_view(),name='cbvdelete')
]

todoproject1/todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todoproject1/todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()

    def __str__(self):
        return  self.name

todoproject1/todoproject/todoapp/forms.py
from .models import Task
from django import forms

class Todofrom(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todoproject1/todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from . models import Task
from .forms import Todofrom
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView

class Tasklistview(ListView):
    model = Task
    template_name='home.html'
    context_object_name = 'task1'

class Taskdetailview(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'

class Taskupdateview(UpdateView):
    model=Task
    template_name = 'edit.html'
    context_object_name = 'task'
    fields = ('name','priority','date')

class Taskdeleteview(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('cbvhome')





    def get_success_url(self):
        return reverse_lazy('cbvdetail',kwargs={'pk':self.object.id})


# Create your views here.
def home(request):
    task1 = Task.objects.all()

    if request.method=='POST':
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        date=request.POST.get('date','')
        task=Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'task':task1})

# def details(request):
#
#     return render(request,'detail.html',)

def delete(request,taskid):
    task=Task.objects.get(id=taskid)
    if request.method == 'POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html')

def update(request,id):
    task=Task.objects.get(id=id)
    f=Todofrom(request.POST or None,instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request,'update.html',{'f':f,'task':task})

todoproject1/todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todoproject1/todoproject/templates/delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure this task is done ?</p>
    <button type="submit">Confirm</button>
</form>
{% endblock %}

todoproject1/todoproject/templates/detail.html
{% extends 'base.html' %}

{% block content %}
            <div class="shadow card">
                <div class="card-body">
                    <h6 class="card-title">{{task.name}}</h6>
                    <p><b>{{task.priority}}</b></p>
                    <p><b>{{task.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' task.id %}">Update</a>

                </div>
            </div>


{% endblock %}

todoproject1/todoproject/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="card">
  <div class="card-header">
    <div class="card-title">Task Update</div>
    <div class="card-body">
      <form method="post">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit">Confirm</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

todoproject1/todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h2>ToDo</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
        <form method="post" class="p-3 shadow">
            {% csrf_token %}

                <div class="form-group">
                <input type="text" class="form-control" name="task" placeholder="Taskname">
                </div>

                <div class="form-group">
                <input type="text" class="form-control" name="priority" placeholder="Enter your priority">
                </div>

                <div class="form-group">
                <input type="date" class="form-control" name="date" placeholder="Enter your Date">
                </div>

                <input type="submit" class="btn btn-success">
        </form>
      </div>
        <div class="col-md-6">
            <h5>Task to be Completed</h5>
             {% for i in task %}
            <div class="shadow card">
                <div class="card-body">
                    <h6 class="card-title">{{i.name}}</h6>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id%}" >Done</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' i.id%}">Update</a>

                </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

todoproject1/todoproject/templates/update.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{f.as_p}}
    <button type="submit">Confirm</button>
</form>
{% endblock %}